add_subdirectory(MathTools)
add_subdirectory(Point)
add_subdirectory(PrimaryEntities)
add_subdirectory(AbstractOperations)
add_subdirectory(Geometry)
add_subdirectory(Geodesic)
add_subdirectory(IOTools)
add_subdirectory(ReachableAreaCalculator)
add_subdirectory(SamplesForTests)
add_subdirectory(TriangularGeometry)
